In [1]:
import os
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt

In [3]:
mainFolder = '/media/ak/Data1/InterestRateFuturesData'
os.listdir(mainFolder)

['Raw Data',
 'ReconstructedLOB',
 'RX1_AllDataFrames.pkl',
 'RX1_cleanLOBLocs.pkl',
 'TSData',
 'TY1_AllDataFrames.pkl',
 'TY1_cleanLOBLocs.pkl',
 'US1_AllDataFrames.pkl',
 'US1_cleanLOBLocs.pkl',
 'UST10y_AllDataFrames.pkl',
 'UST10y_cleanLOBLocs.pkl',
 'UST2y_AllDataFrames.pkl',
 'UST2y_cleanLOBLocs.pkl',
 'UST5y_AllDataFrames.pkl',
 'UST5y_cleanLOBLocs.pkl',
 'XM1_AllDataFrames.pkl',
 'XM1_cleanLOBLocs.pkl',
 'YM1_AllDataFrames.pkl',
 'YM1_cleanLOBLocs.pkl',
 'QuotesTrades',
 'DU1_AllDataFrames.pkl',
 'DU1_cleanLOBLocs.pkl',
 'EventClocksFiles',
 'FB1_AllDataFrames.pkl',
 'FB1_cleanLOBLocs.pkl',
 'FV1_AllDataFrames.pkl',
 'FV1_cleanLOBLocs.pkl',
 'G_1_AllDataFrames.pkl',
 'G_1_cleanLOBLocs.pkl',
 'JB1_AllDataFrames.pkl',
 'JB1_cleanLOBLocs.pkl',
 'Jumps',
 'KE1_AllDataFrames.pkl',
 'KE1_cleanLOBLocs.pkl',
 'MFDCCA',
 'MFDFA',
 'OE1_AllDataFrames.pkl',
 'OE1_cleanLOBLocs.pkl']

In [10]:
EventClocks ='/media/ak/Data1/InterestRateFuturesData/EventClocksFiles'
MFDFA ='/media/ak/Data1/InterestRateFuturesData/MFDFA'
MFDCCA ='/media/ak/Data1/InterestRateFuturesData/MFDCCA'
figuresLocation = '/home/ak/Documents/Research/Papers/StylisedFactsPaper/figures'
ReconstructedLOB = '/media/ak/Data1/InterestRateFuturesData/ReconstructedLOB'

In [15]:
symbols = os.listdir(MFDFA)

# Path to the MFDFA directory
path = MFDFA


def count_files_in_subfolders(directory):
    """Counts files in the subfolders of a given directory."""
    count = 0
    for item in os.listdir(directory):
        item_path = os.path.join(directory, item)
        if os.path.isfile(item_path):
            count += 1
    return count

# Check if the path exists and is a directory
if os.path.exists(path) and os.path.isdir(path):
    # Listing subfolders, their subfolders, and file counts
    subfolder_info = {}
    for folder in os.listdir(path):
        folder_path = os.path.join(path, folder)
        # Check if it is a directory
        if os.path.isdir(folder_path):
            subfolders_count = 0
            total_files_count = 0
            for subfolder in os.listdir(folder_path):
                subfolder_path = os.path.join(folder_path, subfolder)
                if os.path.isdir(subfolder_path):
                    files_count = count_files_in_subfolders(subfolder_path)
                    if files_count > 0:
                        subfolders_count += 1
                        total_files_count += files_count
            # Add information only if there are subfolders with files
            if subfolders_count > 0:
                subfolder_info[folder] = {'Subfolders with Files': subfolders_count, 'Total Files': total_files_count}
else:
    subfolder_info = "Path does not exist or is not a directory"

print(subfolder_info)

{'DU1': {'Subfolders with Files': 2, 'Total Files': 278}, 'FB1': {'Subfolders with Files': 3, 'Total Files': 419}, 'RX1': {'Subfolders with Files': 1, 'Total Files': 27}, 'US1': {'Subfolders with Files': 1, 'Total Files': 157}, 'XM1': {'Subfolders with Files': 2, 'Total Files': 301}, 'YM1': {'Subfolders with Files': 3, 'Total Files': 504}}

In [22]:
FB1 = os.path.join(MFDFA,'FB1')
YM1 = os.path.join(MFDFA,'YM1')
DU1 = os.path.join(MFDFA,'DU1')
clocks = ['dollar', 'tick', 'volume']

In [29]:
FB1_dollar = os.path.join(FB1, 'dollar')
files = os.listdir(FB1_dollar)
testFile =os.path.join(FB1_dollar, files[1])
pd.read_pickle(testFile)['dollar'].keys()

dict_keys(['micro_price_change', 'arrival_rate_median', 'simple_vol', 'median_traded_volume', 'n_F', 'list_H', 'list_H_intercept', 'tau', 'alpha', 'mfSpect'])

In [37]:
df= pd.read_pickle(testFile)
df1= pd.read_pickle(testFile1)

In [34]:
# df1['tick']

In [33]:
df['tick']['median_traded_volume'] - df1['tick']['median_traded_volume']

0       0.0
1       0.0
2       0.0
3       0.0
4       0.0
       ...
1352    NaN
1353    NaN
1354    NaN
1355    NaN
1356    NaN
Name: TradedVolume_median, Length: 1357, dtype: float64

In [20]:
# Create an instance of VolatilityCalculator
calculator = VolatilityCalculator(rolling_window=5)

# Apply the functions on the DataFrame
df = calculator.garman_klass_parkinson_vols(df)
df = calculator.calculate_midquote_returns(df)
df = calculator.compute_spreads(df)

# Print the updated DataFrame
print(df)

              time_first            time_max            time_min  \
0    2018-05-16 00:00:00 2018-05-16 00:00:10 2018-05-16 00:00:00
1    2018-05-16 00:00:11 2018-05-16 00:00:15 2018-05-16 00:00:11
2    2018-05-16 00:00:16 2018-05-16 00:00:25 2018-05-16 00:00:16
3    2018-05-16 00:00:26 2018-05-16 00:00:35 2018-05-16 00:00:26
4    2018-05-16 00:00:36 2018-05-16 00:00:49 2018-05-16 00:00:36
...                  ...                 ...                 ...
5654 2018-05-16 23:53:12 2018-05-16 23:53:57 2018-05-16 23:53:12
5655 2018-05-16 23:53:59 2018-05-16 23:55:53 2018-05-16 23:53:59
5656 2018-05-16 23:55:54 2018-05-16 23:57:57 2018-05-16 23:55:54
5657 2018-05-16 23:57:57 2018-05-16 23:59:01 2018-05-16 23:57:57
5658 2018-05-16 23:59:01 2018-05-16 23:59:58 2018-05-16 23:59:01

               time_last     time_<lambda_0>  BestBid_median  BestAsk_median  \
0    2018-05-16 00:00:10 2018-05-16 00:00:00          97.095          97.100
1    2018-05-16 00:00:15 2018-05-16 00:00:11          97.095          97.100
2    2018-05-16 00:00:25 2018-05-16 00:00:16          97.095          97.100
3    2018-05-16 00:00:35 2018-05-16 00:00:26          97.095          97.100
4    2018-05-16 00:00:49 2018-05-16 00:00:36          97.095          97.100
...                  ...                 ...             ...             ...
5654 2018-05-16 23:53:57 2018-05-16 23:53:12          97.090          97.095
5655 2018-05-16 23:55:53 2018-05-16 23:53:59          97.090          97.095
5656 2018-05-16 23:57:57 2018-05-16 23:55:54          97.090          97.095
5657 2018-05-16 23:59:01 2018-05-16 23:57:57          97.090          97.095
5658 2018-05-16 23:59:58 2018-05-16 23:59:01          97.090          97.095

      MicroPrice_median  arrival_rate_median  MeanRelativeTickVolume_median  \
0             97.098866             0.000012                            0.0
1             97.099055             0.000012                            0.0
2             97.098226             0.000012                            0.0
3             97.098935             0.000012                            0.0
4             97.099188             0.000012                            0.0
...                 ...                  ...                            ...
5654          97.091977             0.000012                            0.0
5655          97.091998             0.000012                            0.0
5656          97.091983             0.000012                            0.0
5657          97.091905             0.000012                            0.0
5658          97.091912             0.000012                            0.0

      ...        log_hl        log_cc  garman_klass_vol  log_hl_squared  \
0     ...  2.412695e-05  6.575406e-06      1.656360e-05    5.821096e-10
1     ...  1.668964e-05 -1.228520e-05      8.998343e-06    2.785441e-10
2     ...  3.305396e-05  1.152133e-05      2.224871e-05    1.092564e-09
3     ...  1.196927e-05  9.263869e-08      8.463358e-06    1.432635e-10
4     ...  1.302846e-05  7.136465e-06      8.074448e-06    1.697407e-10
...   ...           ...           ...               ...             ...
5654  ...  5.338218e-09  5.338218e-09      1.800061e-09    2.849657e-17
5655  ...  0.000000e+00  0.000000e+00      0.000000e+00    0.000000e+00
5656  ...  8.496734e-06  8.496734e-06      2.865121e-06    7.219449e-11
5657  ...  0.000000e+00  0.000000e+00      0.000000e+00    0.000000e+00
5658  ...  1.782397e-05  7.765177e-07      1.259420e-05    3.176938e-10

      parkinson_vol  bipower_var          MQSR          MQAR  EffectiveSpread  \
0           0.00001          NaN           NaN           NaN         0.539417
1           0.00001          NaN  6.726982e-12  2.593643e-06         0.215767
2           0.00001          NaN  7.009193e-11  8.372092e-06         0.485475
3           0.00001          NaN  9.042185e-11  9.509040e-06         0.485475
4           0.00001          NaN  4.595028e-13  6.778663e-07         0.701242
...             ...          ...           ...           ...              ...
5654        0.00001          0.0  2.493674e-10  1.579137e-05         0.323633
5655        0.00001          0.0  2.331874e-10  1.527047e-05         0.000000
5656        0.00001          0.0  1.811859e-11  4.256593e-06         0.107878
5657        0.00001          0.0  1.855380e-11  4.307412e-06         0.000000
5658        0.00001          0.0  2.785973e-10  1.669123e-05         0.431511

      RealizedSpread
0           0.539444
1           0.215756
2           0.485475
3           0.485475
4           0.701242
...              ...
5654             NaN
5655             NaN
5656             NaN
5657             NaN
5658             NaN

[5659 rows x 70 columns]

In [9]:
# import pandas as pd

# def compute_spreads(df: pd.DataFrame) -> pd.DataFrame:
#     bid_plus_offer = df['BASpread_median']
#     bid_plus_offer_shifted = (df['BASpread_median'].shift(-100) + df['BASpread_median'].shift(-100)) / 2
#     dt = pd.to_timedelta(df['time_close'] - df['time_open']).dt.total_seconds() / 3600

#     effective_spread = 2 * dt * (df['TradePrice_median'] - bid_plus_offer)
#     realized_spread = 2 * dt * (df['TradePrice_median'] - bid_plus_offer_shifted)

#     spreads_df = pd.DataFrame({
#         'EffectiveSpread': effective_spread,
#         'RealizedSpread': realized_spread
#     })

#     # Compute the lower and upper percentiles
#     lower_percentile = np.percentile(spreads_df.values, 10)
#     upper_percentile = np.percentile(spreads_df.values, 90)

#     # Replace extreme values with the median
#     spreads_df = np.where((spreads_df < lower_percentile) | (spreads_df > upper_percentile),
#                           np.median(spreads_df[(spreads_df >= lower_percentile) & (spreads_df <= upper_percentile)]),
#                           spreads_df)

#     df[['EffectiveSpread', 'RealizedSpread']] = spreads_df

#     return df

# def calculate_midquote_returns(df: pd.DataFrame) -> pd.DataFrame:
#     midquote = (df['MicroPrice_high'] + df['MicroPrice_low']) / 2

#     mqsr = np.square(np.log(midquote) - np.log(midquote.shift(1)))
#     mqar = np.abs(np.log(midquote) - np.log(midquote.shift(1)))

#     df['MQSR'] = mqsr
#     df['MQAR'] = mqar

#     return df

In [13]:
calculate_midquote_returns(compute_spreads(testdf))

,time_first,time_max,time_min,time_last,time_<lambda_0>,BestBid_median,BestAsk_median,MicroPrice_median,arrival_rate_median,MeanRelativeTickVolume_median,...,MeanRelativeTickVolume_low,MeanRelativeTickVolume_close,OrderImbalance_open,OrderImbalance_high,OrderImbalance_low,OrderImbalance_close,EffectiveSpread,RealizedSpread,MQSR,MQAR
0,2018-05-16 00:00:00,2018-05-16 00:00:10,2018-05-16 00:00:00,2018-05-16 00:00:10,2018-05-16 00:00:00,97.095,97.100,97.098866,0.000012,0.0,...,0.0,0.0,0.546358,0.852912,-0.084164,0.801744,0.539417,0.539444,NaN,NaN
1,2018-05-16 00:00:11,2018-05-16 00:00:15,2018-05-16 00:00:11,2018-05-16 00:00:15,2018-05-16 00:00:11,97.095,97.100,97.099055,0.000012,0.0,...,0.0,0.0,0.638151,0.809218,0.161001,0.161001,0.215767,0.215756,6.726982e-12,2.593643e-06
2,2018-05-16 00:00:16,2018-05-16 00:00:25,2018-05-16 00:00:16,2018-05-16 00:00:25,2018-05-16 00:00:16,97.095,97.100,97.098226,0.000012,0.0,...,0.0,0.0,0.354354,0.801837,-0.481951,0.801837,0.485475,0.485475,7.009193e-11,8.372092e-06
3,2018-05-16 00:00:26,2018-05-16 00:00:35,2018-05-16 00:00:26,2018-05-16 00:00:35,2018-05-16 00:00:26,97.095,97.100,97.098935,0.000012,0.0,...,0.0,0.0,0.758110,0.761708,0.296827,0.761708,0.485475,0.485475,9.042185e-11,9.509040e-06
4,2018-05-16 00:00:36,2018-05-16 00:00:49,2018-05-16 00:00:36,2018-05-16 00:00:49,2018-05-16 00:00:36,97.095,97.100,97.099188,0.000012,0.0,...,0.0,0.0,0.302586,0.808606,0.302586,0.579763,0.701242,0.701242,4.595028e-13,6.778663e-07
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5654,2018-05-16 23:53:12,2018-05-16 23:53:57,2018-05-16 23:53:12,2018-05-16 23:53:57,2018-05-16 23:53:12,97.090,97.095,97.091977,0.000012,0.0,...,0.0,0.0,0.591454,0.591661,0.591454,0.591661,0.323633,NaN,2.493674e-10,1.579137e-05
5655,2018-05-16 23:53:59,2018-05-16 23:55:53,2018-05-16 23:53:59,2018-05-16 23:55:53,2018-05-16 23:53:59,97.090,97.095,97.091998,0.000012,0.0,...,0.0,0.0,-0.001598,-0.001598,-0.001598,-0.001598,0.000000,NaN,2.331874e-10,1.527047e-05
5656,2018-05-16 23:55:54,2018-05-16 23:57:57,2018-05-16 23:55:54,2018-05-16 23:57:57,2018-05-16 23:55:54,97.090,97.095,97.091983,0.000012,0.0,...,0.0,0.0,-0.001279,0.328761,-0.001279,0.328761,0.107878,NaN,1.811859e-11,4.256593e-06
5657,2018-05-16 23:57:57,2018-05-16 23:59:01,2018-05-16 23:57:57,2018-05-16 23:59:01,2018-05-16 23:57:57,97.090,97.095,97.091905,0.000012,0.0,...,0.0,0.0,0.331055,0.331055,0.331055,0.331055,0.000000,NaN,1.855380e-11,4.307412e-06
5658,2018-05-16 23:59:01,2018-05-16 23:59:58,2018-05-16 23:59:01,2018-05-16 23:59:58,2018-05-16 23:59:01,97.090,97.095,97.091912,0.000012,0.0,...,0.0,0.0,-0.001280,0.028883,-0.663448,0.028883,0.431511,NaN,2.785973e-10,1.669123e-05

In [ ]:
jumps = detect_jumps(returnSeries, 0.15)

In [ ]:
plt.plot(jumps.Jump)

In [ ]:
df =testdf
def garman_klass_parkinson_vols(df, rolling_window: int = 5):
    df['log_hl'] = (df['MicroPrice_high'] / df['MicroPrice_low']).replace([np.inf, -np.inf], np.nan).apply(np.log).fillna(0)
    df['log_cc'] = (df['MicroPrice_close'] / df['MicroPrice_open']).replace([np.inf, -np.inf], np.nan).apply(np.log).fillna(0)
    df['garman_klass_vol'] = np.sqrt(0.5 * df['log_hl']**2 - (2*np.log(2) - 1) * df['log_cc']**2) 
    df['log_hl_squared'] = np.log(df['MicroPrice_high'] / df['MicroPrice_low'])**2
    df['parkinson_vol'] = np.sqrt((1 / (4 * np.log(2))) * df['log_hl_squared'].mean())
    df['bipower_var'] = (np.abs(df['log_hl']) * np.abs(df['log_hl'].shift(1))).rolling(rolling_window).sum()
    return df

In [ ]:
import numpy as np

def parkinson_vol(df):
    df['log_hl_squared'] = np.log(df['MicroPrice_high'] / df['MicroPrice_low'])**2
    df['parkinson_vol'] = np.sqrt((1 / (4 * np.log(2))) * df['log_hl_squared'].mean())
    return df

In [ ]:
df =garman_klass_parkinson_vols(testdf)

In [ ]:
compute_spreads(df).columns.values

In [ ]:
compute_spreads(df).describe()

In [ ]:
plt.plot(df.bipower_var)

In [ ]:
# Add Garman-Klass volatility calculation
# Replace 'TradePrice_close' and 'TradePrice_open' with the actual column names you want to use in your DataFrame
resampled_df['period'] = (pd.to_datetime(resampled_df['time_last']) - pd.to_datetime(resampled_df['time_first'])).dt.total_seconds() / (24 * 60 * 60)
resampled_df['log_hl'] = np.where((resampled_df['BestBid_high'] != resampled_df['BestBid_low']), np.log(resampled_df['BestBid_high'] / resampled_df['BestBid_low']), 0)
resampled_df['log_cc'] = np.where((resampled_df['TradePrice_close'] != resampled_df['TradePrice_open']), np.log(resampled_df['TradePrice_close'] / resampled_df['TradePrice_open']), 0)
resampled_df['garman_klass_vol'] = np.sqrt(0.5 * resampled_df['log_hl']**2 - (2*np.log(2) - 1) * resampled_df['log_cc']**2)

In [ ]:
_=plt.plot(df.garman_klass_vol)

In [ ]:
import numpy as np
import pandas as pd



def garman_klass(df, clean=True):
    df.fillna(value=mean_value, inplace=True)
    df['period'] = (pd.to_datetime(df['time_close']) - pd.to_datetime(df['time_open'])).dt.total_seconds() / (24 * 60 * 60)
    df['log_hl'] = (df['MicroPrice_high'] / df['MicroPrice_low']).replace([np.inf, -np.inf], np.nan).apply(np.log).fillna(0)
    df['log_cc'] = (df['MicroPrice_close'] / df['MicroPrice_open']).replace([np.inf, -np.inf], np.nan).apply(np.log).fillna(0)
    df['garman_klass_vol'] = np.sqrt(0.5 * df['log_hl']**2 - (2*np.log(2) - 1) * df['log_cc']**2) / np.sqrt(df['period']).replace([np.inf, -np.inf], np.nan).fillna(0)
#     if clean:
#         df = df.dropna()
    return df


# # Use the function on your DataFrame
# df = garman_klass(df)

In [ ]:
testdf.columns

In [ ]:
_=plt.hist((testdf['OrderImbalance_open']+testdf['OrderImbalance_close']/2), bins =200)

In [ ]:
# Create an instance of VolatilityMetrics
metrics = VolatilityMetrics()

In [ ]:
# Function: parkinson
dataframe = testdf
parkinson_df = metrics.parkinson(dataframe)
print("Parkinson DataFrame:\n", parkinson_df)

In [39]:
## testing

In [40]:
import os
import pandas as pd
import numpy as np

In [41]:
t7folder ='/media/ak/T7/FuturesDataSemiProcessed/RX1'

In [42]:
files = os.listdir(t7folder)

In [44]:
file = os.path.join(t7folder, files[10])

In [46]:
testFileDict =pd.read_pickle(file)

In [47]:
testFileDict.keys()

dict_keys(['20180529'])

In [50]:
testFileDict['20180529']['tick']

,BidSize_open,BidSize_high,BidSize_low,BidSize_close,QuoteTime_open,QuoteTime_high,QuoteTime_low,QuoteTime_close,type_x_open,type_x_high,...,dollar_traded_volume_low,dollar_traded_volume_close,timeStampIdx_open,timeStampIdx_high,timeStampIdx_low,timeStampIdx_close,micro_price_open,micro_price_high,micro_price_low,micro_price_close
tick_bucket,,,,,,,,,,,,,,,,,,,,,
1.0,5,632,1,159,2018-05-04 06:01:14.943,2018-05-04 06:01:28.749,2018-05-04 06:01:14.943,2018-05-04 06:01:28.749,BID,BID,...,159.17,795.90,2018-05-04 06:01:14.850,2018-05-04 06:01:28.749,2018-05-04 06:01:14.850,2018-05-04 06:01:28.749,159.179675,159.189866,159.160342,159.172050
2.0,54,656,1,656,2018-05-04 06:01:28.939,2018-05-04 06:02:01.878,2018-05-04 06:01:28.939,2018-05-04 06:02:01.878,BID,BID,...,159.15,159.15,2018-05-04 06:01:28.939,2018-05-04 06:02:01.149,2018-05-04 06:01:28.939,2018-05-04 06:02:01.149,159.170000,159.179820,159.150017,159.155297
3.0,229,655,32,57,2018-05-04 06:02:01.924,2018-05-04 06:03:04.319,2018-05-04 06:02:01.924,2018-05-04 06:03:04.319,BID,BID,...,159.15,159.17,2018-05-04 06:02:01.924,2018-05-04 06:03:04.021,2018-05-04 06:02:01.924,2018-05-04 06:03:04.021,159.157696,159.169371,159.151463,159.167585
4.0,51,358,2,18,2018-05-04 06:03:04.329,2018-05-04 06:04:06.250,2018-05-04 06:03:04.329,2018-05-04 06:04:06.250,BID,BID,...,159.15,318.32,2018-05-04 06:03:04.021,2018-05-04 06:04:06.250,2018-05-04 06:03:04.021,2018-05-04 06:04:06.250,159.167783,159.169934,159.150083,159.169477
5.0,20,60,2,55,2018-05-04 06:04:06.250,2018-05-04 06:04:23.257,2018-05-04 06:04:06.250,2018-05-04 06:04:23.257,BID,BID,...,159.17,159.17,2018-05-04 06:04:06.250,2018-05-04 06:04:23.079,2018-05-04 06:04:06.250,2018-05-04 06:04:23.079,159.169422,159.169936,159.168165,159.168292
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10257.0,14,37,1,11,2018-05-29 19:53:23.473,2018-05-29 19:54:47.882,2018-05-29 19:53:23.473,2018-05-29 19:54:47.882,BID,BID,...,163.38,326.82,2018-05-29 19:53:23.473,2018-05-29 19:54:47.882,2018-05-29 19:53:23.473,2018-05-29 19:54:47.882,163.384167,163.414500,163.371111,163.414500
10258.0,12,37,1,2,2018-05-29 19:54:47.882,2018-05-29 19:55:05.383,2018-05-29 19:54:47.882,2018-05-29 19:55:05.383,BID,BID,...,163.40,326.80,2018-05-29 19:54:47.882,2018-05-29 19:55:04.721,2018-05-29 19:54:47.882,2018-05-29 19:55:04.721,163.414286,163.427755,163.390476,163.408571
10259.0,3,26,1,12,2018-05-29 19:55:05.385,2018-05-29 19:56:31.867,2018-05-29 19:55:05.385,2018-05-29 19:56:31.867,BID,BID,...,163.39,326.78,2018-05-29 19:55:04.721,2018-05-29 19:56:31.867,2018-05-29 19:55:04.721,2018-05-29 19:56:31.867,163.408000,163.409231,163.381111,163.390769
10260.0,13,19,1,7,2018-05-29 19:56:31.868,2018-05-29 19:57:56.432,2018-05-29 19:56:31.868,2018-05-29 19:57:56.432,BID,BID,...,163.39,490.17,2018-05-29 19:56:31.867,2018-05-29 19:57:56.432,2018-05-29 19:56:31.867,2018-05-29 19:57:56.432,163.390714,163.428889,163.382308,163.383000
10261.0,6,38,1,24,2018-05-29 19:57:56.432,2018-05-29 19:58:28.336,2018-05-29 19:57:56.432,2018-05-29 19:58:28.336,BID,BID,...,163.34,163.37,2018-05-29 19:57:56.432,2018-05-29 19:58:28.335,2018-05-29 19:57:56.432,2018-05-29 19:58:28.335,163.383333,163.389091,163.330769,163.358824

In [51]:
## raw data testing

In [32]:
rawdatafolder = '/media/ak/Data1/raw bloomberg data/'

In [33]:
import os

def get_subfolder_lengths(folder_path):
    for root, dirs, files in os.walk(folder_path):
        if root != folder_path:  # Exclude the main folder
            subfolder_name = os.path.basename(root)
            subfolder_length = len(dirs) + len(files)
            print(f"Subfolder '{subfolder_name}': {subfolder_length} items")

# Provide the path to the folder you want to analyze
folder_path = "/path/to/folder"

get_subfolder_lengths(rawdatafolder)

Subfolder 'DU1_Comdty-20181028': 139 items
Subfolder 'FB1_Comdty-20181028': 139 items
Subfolder 'FV1_Comdty-20181028': 141 items
Subfolder 'G_1_Comdty-20181028': 136 items
Subfolder 'JB1_Comdty-20181028': 140 items
Subfolder 'KE1_Comdty-20181028': 139 items
Subfolder 'OE1_Comdty-20181028': 139 items
Subfolder 'RX1_Comdty-20181028': 139 items
Subfolder 'TU1_Comdty-20181028': 141 items
Subfolder 'TY1_Comdty-20181028': 108 items
Subfolder 'UST10y': 141 items
Subfolder 'UST5y': 141 items
Subfolder 'VIX_Index-20181027': 137 items

In [57]:
file = os.path.join(rawdatafolder, 'G_1_Comdty-20181028','G_1_Comdty-20180417.csv' )

In [80]:
dfTest =pd.read_csv(file)

In [83]:
trades = dfTest[dfTest['type']=='TRADE']
quotes = dfTest[dfTest['type']!='TRADE']

In [84]:
quotes

        Unnamed: 0  size                     time type   value
63              63     4  2018-04-17 07:00:00.279  BID  121.81
64              64     6  2018-04-17 07:00:00.279  ASK  121.82
67              67     8  2018-04-17 07:00:00.302  BID  121.79
68              68    11  2018-04-17 07:00:00.302  ASK  121.81
69              69    12  2018-04-17 07:00:00.330  ASK  121.81
...            ...   ...                      ...  ...     ...
163639      163639   198  2018-04-17 17:00:00.058  BID  122.09
163640      163640     0  2018-04-17 17:00:00.270  BID    0.00
163641      163641     0  2018-04-17 17:00:00.270  ASK    0.00
163642      163642     0  2018-04-17 17:00:00.000  BID  122.09
163643      163643     0  2018-04-17 17:00:00.000  ASK  122.12

[101617 rows x 5 columns]

In [65]:
irf = '/media/ak/Data/InterestRateFuturesData'
quotesTrades = os.path.join(irf, 'QuotesTrades'

In [79]:
# columns need to be like : ['Unnamed: 0', 'size', 'time', 'type', 'value']

array(['Unnamed: 0', 'size', 'time', 'type', 'value'], dtype=object)

In [86]:
os.listdir(quotesTrades)

['DU1', 'FB1', 'G_1', 'RX1', 'SI1', 'TY1', 'US1', 'UST2y', 'VXX', 'XM1', 'YM1']

In [87]:
string = '/media/ak/Data/raw bloomberg data/RX1_Comdty-20181028'

In [94]:
string.split("/")[-1].split("-")[0].split("_")[0]

'RX1'

In [97]:
pd.read_csv('/media/ak/Data/InterestRateFuturesData/QuotesTrades/JB1/JB1_Comdty_trades/20180821.csv')

      size                 time   type   value
0        1  2018-08-21 00:00:20  Trade  150.52
1        1  2018-08-21 00:00:21  Trade  150.52
2        2  2018-08-21 00:00:26  Trade  150.53
3        1  2018-08-21 00:00:34  Trade  150.52
4        1  2018-08-21 00:00:34  Trade  150.52
...    ...                  ...    ...     ...
3492     1  2018-08-21 23:59:51  Trade  150.51
3493    40  2018-08-21 23:59:57  Trade  150.51
3494    50  2018-08-21 23:59:57  Trade  150.51
3495    15  2018-08-21 23:59:57  Trade  150.51
3496     7  2018-08-22 00:00:00  Trade  150.51

[3497 rows x 4 columns]

In [104]:



get_subfolder_lengths('/media/ak/Data/InterestRateFuturesData/QuotesTrades')

Subfolder 'DU1': 2 items
Subfolder 'DU1_Comdty_quotes': 140 items
Subfolder 'DU1_Comdty_trades': 140 items
Subfolder 'FB1': 2 items
Subfolder 'FB1_Comdty_quotes': 136 items
Subfolder 'FB1_Comdty_trades': 139 items
Subfolder 'FV1': 2 items
Subfolder 'FV1_Comdty_quotes': 141 items
Subfolder 'FV1_Comdty_trades': 141 items
Subfolder 'G': 2 items
Subfolder 'G_Comdty_quotes': 136 items
Subfolder 'G_Comdty_trades': 136 items
Subfolder 'JB1': 2 items
Subfolder 'JB1_Comdty_quotes': 140 items
Subfolder 'JB1_Comdty_trades': 140 items
Subfolder 'KE1': 2 items
Subfolder 'KE1_Comdty_quotes': 139 items
Subfolder 'KE1_Comdty_trades': 139 items
Subfolder 'OE1': 2 items
Subfolder 'OE1_Comdty_quotes': 139 items
Subfolder 'OE1_Comdty_trades': 139 items
Subfolder 'RX1': 2 items
Subfolder 'RX1_Comdty_quotes': 139 items
Subfolder 'RX1_Comdty_trades': 139 items
Subfolder 'SI1': 1 items
Subfolder 'SI1_Comdty_Trades': 141 items
Subfolder 'TY1': 2 items
Subfolder 'TY1_Comdty_quotes': 108 items
Subfolder 'TY1_Comdty_trades': 108 items
Subfolder 'US1': 2 items
Subfolder 'US1_Comdty_quotes': 141 items
Subfolder 'US1_Comdty_trades': 141 items
Subfolder 'UST2y': 2 items
Subfolder 'UST2y_Comdty_quotes': 139 items
Subfolder 'UST2y_Comdty_trades': 139 items
Subfolder 'VXX': 3 items
Subfolder 'VXX_US_Equity': 126 items
Subfolder 'VXX_US_Equity_quotes': 126 items
Subfolder 'VXX_US_Equity_trades': 126 items
Subfolder 'XM1': 2 items
Subfolder 'XM1_Comdty_quotes': 140 items
Subfolder 'XM1_Comdty_trades': 140 items
Subfolder 'YM1': 2 items
Subfolder 'YM1_Comdty_quotes': 141 items
Subfolder 'YM1_Comdty_trades': 141 items

In [121]:
folder = '/media/ak/Data/InterestRateFuturesData/ReconstructedLOB/FV1'
files = os.listdir('/media/ak/Data/InterestRateFuturesData/ReconstructedLOB/FV1')

In [122]:
testFile = os.path.join(folder, files[15])
df =pd.read_pickle(testFile)

In [123]:
df.shape

(72814, 30)

In [124]:
df.tail(10)

,time,estimated_arrival_time,TradePrice,TradedVolume,NoOfTrades,arrival_rate,AverageVolumePerTrade,date,CCYTradedVolume,type,...,RunningNoOfTrades,RunningCumlVolume,RunningCumlNoOfTrades,MicroPrice,BASpread,QuoteSize,MidPrice,OrderImbalance,ExpandingMeanRelativeTickVolume,MeanRelativeTickVolume
3970876,2018-05-02 23:56:07,1726-01-22 00:07:47.145224192,113.4375,1.0,1.0,0.000012,1.0,2018-05-02,113.4375,BID,...,1.0,8.206333e+07,30077.0,113.438426,0.007812,3078.0,113.441406,-0.762833,0.00000,0.000000
3937944,2018-05-02 23:56:27,1726-01-22 00:07:47.145224192,113.4375,1.0,1.0,0.000012,1.0,2018-05-02,113.4375,ASK,...,1.0,8.206333e+07,30077.0,113.441322,0.007812,746.0,113.441406,-0.021448,0.00000,0.000000
3970877,2018-05-02 23:57:49,1726-01-22 00:07:47.145224192,113.4375,1.0,1.0,0.000012,1.0,2018-05-02,113.4375,BID,...,1.0,8.206333e+07,30077.0,113.441312,0.007812,744.0,113.441406,-0.024194,0.00000,0.000000
3937945,2018-05-02 23:57:49,1726-01-22 00:07:47.145224192,113.4375,1.0,1.0,0.000012,1.0,2018-05-02,113.4375,ASK,...,1.0,8.206333e+07,30077.0,113.442985,0.007812,517.0,113.441406,0.404255,0.00000,0.000000
445147,2018-05-02 23:57:49,1726-01-22 00:10:32.145224192,113.4375,2.0,1.0,0.000012,2.0,2018-05-02,226.8750,Trade,...,1.0,8.206356e+07,30078.0,113.442985,0.007812,517.0,113.441406,0.404255,0.20119,0.201204
3937946,2018-05-02 23:58:59,1726-01-22 00:10:32.145224192,113.4375,2.0,1.0,0.000012,2.0,2018-05-02,226.8750,ASK,...,1.0,8.206356e+07,30078.0,113.442943,0.007812,521.0,113.441406,0.393474,0.00000,0.000000
3937947,2018-05-02 23:59:14,1726-01-22 00:10:32.145224192,113.4375,2.0,1.0,0.000012,2.0,2018-05-02,226.8750,ASK,...,1.0,8.206356e+07,30078.0,113.441586,0.007812,694.0,113.441406,0.046110,0.00000,0.000000
3937948,2018-05-02 23:59:25,1726-01-22 00:10:32.145224192,113.4375,2.0,1.0,0.000012,2.0,2018-05-02,226.8750,ASK,...,1.0,8.206356e+07,30078.0,113.442831,0.007812,532.0,113.441406,0.364662,0.00000,0.000000
3937949,2018-05-02 23:59:29,1726-01-22 00:10:32.145224192,113.4375,2.0,1.0,0.000012,2.0,2018-05-02,226.8750,ASK,...,1.0,8.206356e+07,30078.0,113.439653,0.007812,1317.0,113.441406,-0.448747,0.00000,0.000000
3937950,2018-05-02 23:59:30,1726-01-22 00:10:32.145224192,113.4375,2.0,1.0,0.000012,2.0,2018-05-02,226.8750,ASK,...,1.0,8.206356e+07,30078.0,113.440760,0.007812,870.0,113.441406,-0.165517,0.00000,0.000000

In [129]:
import os

def get_unique_elements(directory, subdirectory1, subdirectory2):
    path1 = os.path.join(directory, subdirectory1)
    path2 = os.path.join(directory, subdirectory2)
    
    if not os.path.isdir(path1) or not os.path.isdir(path2):
        print("Error: One or both subdirectories do not exist.")
        return []
    
    elements1 = set(os.listdir(path1))
    elements2 = set(os.listdir(path2))
    
    unique_elements = elements1.symmetric_difference(elements2)
    return unique_elements

# Usage example
directory = '/media/ak/Data/InterestRateFuturesData/QuotesTrades/KE1'
subdirectory1 = 'KE1_Comdty_quotes'
subdirectory2 = 'KE1_Comdty_trades'

unique_elements = get_unique_elements(directory, subdirectory1, subdirectory2)
print(unique_elements)

set()

In [130]:
import os

def create_subdirectories(main_directory, subdirectory_names):
    # Create the main directory if it doesn't exist
    if not os.path.exists(main_directory):
        os.makedirs(main_directory)

    # Create subdirectories within the main directory
    for name in subdirectory_names:
        subdirectory_path = os.path.join(main_directory, name)
        os.makedirs(subdirectory_path)
        print(f"Created subdirectory: {subdirectory_path}")

In [132]:
EventClocks ='/media/ak/Data/InterestRateFuturesData/EventClocksFiles'
os.listdir(EventClocks)

['DU1', 'FB1', 'FV1', 'JB1', 'KE1', 'OE1', 'RX1', 'US1', 'US2y', 'XM1', 'YM1']

In [134]:

# Example usage
main_directory = "/media/ak/Data/InterestRateFuturesData/MFDCCA"
subdirectory_names = ['DU1', 'FB1', 'FV1', 'JB1', 'KE1', 'OE1', 'RX1', 'TY1', 
                      'US1', 'UST2y', 'XM1', 'YM1', 'UST5y','UST10y',]

create_subdirectories(main_directory, subdirectory_names)

Created subdirectory: /media/ak/Data/InterestRateFuturesData/MFDCCA/DU1
Created subdirectory: /media/ak/Data/InterestRateFuturesData/MFDCCA/FB1
Created subdirectory: /media/ak/Data/InterestRateFuturesData/MFDCCA/FV1
Created subdirectory: /media/ak/Data/InterestRateFuturesData/MFDCCA/JB1
Created subdirectory: /media/ak/Data/InterestRateFuturesData/MFDCCA/KE1
Created subdirectory: /media/ak/Data/InterestRateFuturesData/MFDCCA/OE1
Created subdirectory: /media/ak/Data/InterestRateFuturesData/MFDCCA/RX1
Created subdirectory: /media/ak/Data/InterestRateFuturesData/MFDCCA/TY1
Created subdirectory: /media/ak/Data/InterestRateFuturesData/MFDCCA/US1
Created subdirectory: /media/ak/Data/InterestRateFuturesData/MFDCCA/UST2y
Created subdirectory: /media/ak/Data/InterestRateFuturesData/MFDCCA/XM1
Created subdirectory: /media/ak/Data/InterestRateFuturesData/MFDCCA/YM1
Created subdirectory: /media/ak/Data/InterestRateFuturesData/MFDCCA/UST5y
Created subdirectory: /media/ak/Data/InterestRateFuturesData/MFDCCA/UST10y

In [1]:
import os
import pandas as pd
import numpy as np

In [2]:
testDirt = '/media/ak/Data/ExperimentData/August11th2022Experiments/ExperimentInputFiles/outputs'

In [5]:
testFile = os.path.join(testDirt,  'G_1_tick_100_output.json')

In [20]:
testFiles = os.listdir(testDirt)
idx=10
testFileLoc = os.path.join(testDirt, testFiles[idx])

In [21]:
import json
  
# Opening JSON file
f = open(testFileLoc )
  
# returns JSON object as 
# a dictionary
data = json.load(f)

In [22]:
data.keys()

dict_keys(['n', 'rho', 'F', 'H', 'H_intercept'])

In [23]:
len(data['rho'])

50

In [24]:
pd.DataFrame.from_dict(data)

      n       rho         F         H  H_intercept
0    10  0.018321  0.000490  1.386677   -10.401392
1    30  0.004534  0.003324  1.386677   -10.401392
2    50 -0.014164  0.007008  1.386677   -10.401392
3    70 -0.019350  0.011619  1.386677   -10.401392
4    90 -0.048530  0.016096  1.386677   -10.401392
5   110 -0.064619  0.021372  1.386677   -10.401392
6   130 -0.044644  0.027905  1.386677   -10.401392
7   150 -0.046058  0.033730  1.386677   -10.401392
8   170 -0.071922  0.041117  1.386677   -10.401392
9   190 -0.104262  0.047559  1.386677   -10.401392
10  210 -0.133303  0.059247  1.386677   -10.401392
11  230 -0.158234  0.071929  1.386677   -10.401392
12  250 -0.011309  0.064086  1.386677   -10.401392
13  270 -0.072689  0.074173  1.386677   -10.401392
14  290 -0.152904  0.099232  1.386677   -10.401392
15  310 -0.163089  0.102988  1.386677   -10.401392
16  330 -0.155984  0.111800  1.386677   -10.401392
17  350 -0.110055  0.121274  1.386677   -10.401392
18  370  0.010548  0.105803  1.386677   -10.401392
19  390 -0.203817  0.122357  1.386677   -10.401392
20  410  0.035828  0.115721  1.386677   -10.401392
21  430 -0.167344  0.173274  1.386677   -10.401392
22  450 -0.223454  0.137372  1.386677   -10.401392
23  470 -0.199043  0.164989  1.386677   -10.401392
24  490  0.048659  0.153155  1.386677   -10.401392
25  510 -0.099772  0.135648  1.386677   -10.401392
26  530 -0.158866  0.190903  1.386677   -10.401392
27  550 -0.014600  0.147704  1.386677   -10.401392
28  570 -0.185739  0.222569  1.386677   -10.401392
29  590 -0.300033  0.195046  1.386677   -10.401392
30  610 -0.253054  0.225852  1.386677   -10.401392
31  630 -0.097743  0.234953  1.386677   -10.401392
32  650 -0.152919  0.225961  1.386677   -10.401392
33  670 -0.034817  0.251418  1.386677   -10.401392
34  690 -0.215592  0.259008  1.386677   -10.401392
35  710 -0.162534  0.258938  1.386677   -10.401392
36  730 -0.023826  0.248978  1.386677   -10.401392
37  750 -0.048769  0.246302  1.386677   -10.401392
38  770 -0.028856  0.274153  1.386677   -10.401392
39  790  0.055525  0.285260  1.386677   -10.401392
40  810 -0.139742  0.323907  1.386677   -10.401392
41  830 -0.055003  0.376917  1.386677   -10.401392
42  850 -0.062849  0.362402  1.386677   -10.401392
43  870 -0.122565  0.337064  1.386677   -10.401392
44  890 -0.015163  0.332197  1.386677   -10.401392
45  910  0.063167  0.352359  1.386677   -10.401392
46  930  0.029269  0.360472  1.386677   -10.401392
47  950 -0.077629  0.403610  1.386677   -10.401392
48  970 -0.087093  0.434666  1.386677   -10.401392
49  990 -0.062027  0.455545  1.386677   -10.401392