In [1]:
import os
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt

In [2]:
EventClocks ='/media/ak/Data1/InterestRateFuturesData/EventClocksFiles'

In [36]:
testFile ='/media/ak/Data/InterestRateFuturesData/MFDFA/US1/tick/20180715_mfdfa.pkl'
testFile1 ='/media/ak/Data/InterestRateFuturesData/MFDFA/YM1/tick/20180730_mfdfa.pkl'

In [37]:
df= pd.read_pickle(testFile)
df1= pd.read_pickle(testFile1)

In [38]:
df1['tick']

{'micro_price_change': 0       0.000000e+00
 1       1.226809e-08
 2       2.158303e-05
 3      -1.414421e-05
 4      -1.877176e-05
             ...
 3249   -3.952247e-08
 3250   -1.022097e-05
 3251   -3.429202e-06
 3252    1.137241e-05
 3253    1.889903e-08
 Name: pct_changes, Length: 3254, dtype: float64,
 'arrival_rate_median': 0            NaN
 1       0.000059
 2       0.000059
 3       0.000059
 4       0.000059
           ...
 3249    0.000035
 3250    0.000035
 3251    0.000035
 3252    0.000035
 3253    0.000035
 Name: arrival_rate_median, Length: 3254, dtype: float64,
 'simple_vol': 0            NaN
 1            NaN
 2       0.003905
 3       0.005026
 4       0.001809
           ...
 3249    0.000760
 3250    0.002683
 3251    0.002191
 3252    0.003235
 3253    0.002833
 Name: simple_vol, Length: 3254, dtype: float64,
 'median_traded_volume': 0         NaN
 1       124.0
 2       124.0
 3       124.0
 4       124.0
         ...
 3249    162.0
 3250    162.0
 3251    162.0
 3252    162.0
 3253    162.0
 Name: TradedVolume_median, Length: 3254, dtype: float64,
 'n_F': {5: array([3.33832067e-19, 5.08353809e-19, 7.52777888e-19, ...,
         5.86859535e-05, 5.86879439e-05, 5.86859738e-05]),
  6: array([3.59639870e-19, 5.50872986e-19, 8.14285311e-19, ...,
         5.86859539e-05, 5.86879440e-05, 5.86859739e-05]),
  7: array([3.89508612e-19, 6.00383411e-19, 8.85773652e-19, ...,
         5.86859543e-05, 5.86879441e-05, 5.86859739e-05]),
  8: array([4.24357963e-19, 6.58528498e-19, 9.69563009e-19, ...,
         5.86859547e-05, 5.86879442e-05, 5.86859739e-05]),
  9: array([4.65382224e-19, 7.27459147e-19, 1.06868275e-18, ...,
         5.86859551e-05, 5.86879443e-05, 5.86859739e-05]),
  10: array([5.14153531e-19, 8.10030492e-19, 1.18714395e-18, ...,
         5.86859554e-05, 5.86879444e-05, 5.86859740e-05]),
  11: array([5.72772491e-19, 9.10091774e-19, 1.33033960e-18, ...,
         5.86859558e-05, 5.86879445e-05, 5.86859740e-05]),
  12: array([6.44092380e-19, 1.03292218e-18, 1.50564451e-18, ...,
         5.86859562e-05, 5.86879446e-05, 5.86859740e-05]),
  13: array([7.32060131e-19, 1.18590096e-18, 1.72333472e-18, ...,
         5.86859566e-05, 5.86879447e-05, 5.86859740e-05]),
  14: array([8.42247477e-19, 1.37956349e-18, 1.99803126e-18, ...,
         5.86859570e-05, 5.86879448e-05, 5.86859741e-05]),
  15: array([9.82700510e-19, 1.62931215e-18, 2.35103006e-18, ...,
         5.86859574e-05, 5.86879449e-05, 5.86859741e-05]),
  16: array([1.16533940e-18, 1.95827413e-18, 2.81417792e-18, ...,
         5.86859577e-05, 5.86879450e-05, 5.86859741e-05]),
  17: array([1.40834258e-18, 2.40224354e-18, 3.43654440e-18, ...,
         5.86859581e-05, 5.86879451e-05, 5.86859741e-05]),
  18: array([1.74036356e-18, 3.01856823e-18, 4.29635987e-18, ...,
         5.86859585e-05, 5.86879452e-05, 5.86859742e-05]),
  19: array([2.20831560e-18, 3.90285985e-18, 5.52333875e-18, ...,
         5.86859589e-05, 5.86879453e-05, 5.86859742e-05]),
  20: array([2.89246813e-18, 5.22206784e-18, 7.34259395e-18, ...,
         5.86859593e-05, 5.86879454e-05, 5.86859742e-05]),
  21: array([3.93744193e-18, 7.28396270e-18, 1.01662625e-17, ...,
         5.86859596e-05, 5.86879454e-05, 5.86859742e-05]),
  22: array([5.62024804e-18, 1.06936894e-17, 1.47983538e-17, ...,
         5.86859600e-05, 5.86879455e-05, 5.86859743e-05]),
  23: array([8.51197979e-18, 1.67371197e-17, 2.29319424e-17, ...,
         5.86859604e-05, 5.86879456e-05, 5.86859743e-05]),
  24: array([1.39006159e-17, 2.84188948e-17, 3.84817738e-17, ...,
         5.86859608e-05, 5.86879457e-05, 5.86859743e-05]),
  25: array([2.50341168e-17, 5.36437261e-17, 7.16196461e-17, ...,
         5.86859612e-05, 5.86879458e-05, 5.86859743e-05]),
  26: array([5.13540433e-17, 1.16612314e-16, 1.53024061e-16, ...,
         5.86859615e-05, 5.86879459e-05, 5.86859744e-05]),
  27: array([1.25923251e-16, 3.07805409e-16, 3.95293030e-16, ...,
         5.86859619e-05, 5.86879460e-05, 5.86859744e-05]),
  28: array([3.97874457e-16, 1.07212535e-15, 1.33917787e-15, ...,
         5.86859623e-05, 5.86879461e-05, 5.86859744e-05]),
  29: array([1.83310047e-15, 5.66065725e-15, 6.81385610e-15, ...,
         5.86859627e-05, 5.86879462e-05, 5.86859744e-05]),
  30: array([1.53266864e-14, 5.81326582e-14, 6.64447463e-14, ...,
         5.86859631e-05, 5.86879463e-05, 5.86859744e-05]),
  31: array([3.55826043e-13, 1.89870252e-12, 2.00904459e-12, ...,
         5.86859635e-05, 5.86879464e-05, 5.86859745e-05]),
  32: array([5.42982909e-11, 5.05144815e-10, 4.78215546e-10, ...,
         5.86859638e-05, 5.86879465e-05, 5.86859745e-05]),
  33: array([6.29997688e-08, 4.03328352e-07, 3.99274808e-07, ...,
         5.86859642e-05, 5.86879466e-05, 5.86859745e-05]),
  34: array([1.79252756e-06, 3.03530876e-06, 3.44943735e-06, ...,
         5.86859646e-05, 5.86879467e-05, 5.86859745e-05]),
  35: array([2.45676119e-06, 2.28514387e-07, 1.70704246e-07, ...,
         5.82946637e-05, 5.82946637e-05, 5.82946637e-05]),
  36: array([3.37418518e-06, 4.14880125e-06, 4.72833044e-06, ...,
         5.86859654e-05, 5.86879469e-05, 5.86859746e-05]),
  37: array([3.63724455e-06, 4.37423088e-06, 4.94860306e-06, ...,
         5.86859657e-05, 5.86879470e-05, 5.86859746e-05]),
  38: array([3.87608186e-06, 4.59441473e-06, 5.16645521e-06, ...,
         5.86859661e-05, 5.86879471e-05, 5.86859746e-05]),
  39: array([4.11559736e-06, 4.82399836e-06, 5.39911876e-06, ...,
         5.86859665e-05, 5.86879472e-05, 5.86859747e-05]),
  40: array([4.36776573e-06, 5.07324200e-06, 5.65790483e-06, ...,
         5.86859669e-05, 5.86879473e-05, 5.86859747e-05]),
  41: array([4.64305024e-06, 5.35351630e-06, 5.95522213e-06, ...,
         5.86859673e-05, 5.86879474e-05, 5.86859747e-05]),
  42: array([4.95322422e-06, 5.67910097e-06, 6.30657632e-06, ...,
         5.86859676e-05, 5.86879475e-05, 5.86859747e-05]),
  43: array([5.31261493e-06, 6.06843520e-06, 6.73172302e-06, ...,
         5.86859680e-05, 5.86879476e-05, 5.86859748e-05]),
  44: array([5.73885211e-06, 6.54514480e-06, 7.25540674e-06, ...,
         5.86859684e-05, 5.86879477e-05, 5.86859748e-05]),
  45: array([6.25317959e-06, 7.13862095e-06, 7.90745041e-06, ...,
         5.86859688e-05, 5.86879478e-05, 5.86859748e-05]),
  46: array([6.88010693e-06, 7.88366753e-06, 8.72174240e-06, ...,
         5.86859692e-05, 5.86879479e-05, 5.86859748e-05]),
  47: array([7.64612277e-06, 8.81866211e-06, 9.73371895e-06, ...,
         5.86859696e-05, 5.86879480e-05, 5.86859749e-05]),
  48: array([8.57735764e-06, 9.98196238e-06, 1.09763628e-05, ...,
         5.86859699e-05, 5.86879481e-05, 5.86859749e-05]),
  49: array([9.69647848e-06, 1.14070156e-05, 1.24754725e-05, ...,
         5.86859703e-05, 5.86879482e-05, 5.86859749e-05]),
  50: array([1.10195544e-05, 1.31174748e-05, 1.42455806e-05, ...,
         5.86859707e-05, 5.86879483e-05, 5.86859749e-05]),
  51: array([1.25538318e-05, 1.51239372e-05, 1.62878724e-05, ...,
         5.86859711e-05, 5.86879484e-05, 5.86859750e-05]),
  52: array([1.42970779e-05, 1.74233100e-05, 1.85906630e-05, ...,
         5.86859715e-05, 5.86879485e-05, 5.86859750e-05]),
  53: array([1.62385426e-05, 2.00006728e-05, 2.11319690e-05, ...,
         5.86859718e-05, 5.86879485e-05, 5.86859750e-05]),
  54: array([1.83610312e-05, 2.28326276e-05, 2.38830996e-05, ...,
         5.86859722e-05, 5.86879486e-05, 5.86859750e-05]),
  55: array([2.06433742e-05, 2.58909541e-05, 2.68122119e-05, ...,
         5.86859726e-05, 5.86879487e-05, 5.86859751e-05]),
  56: array([2.30627055e-05, 2.91457392e-05, 2.98871771e-05, ...,
         5.86859730e-05, 5.86879488e-05, 5.86859751e-05]),
  57: array([2.55962303e-05, 3.25676309e-05, 3.30775388e-05, ...,
         5.86859734e-05, 5.86879489e-05, 5.86859751e-05]),
  58: array([2.82224096e-05, 3.61292258e-05, 3.63556384e-05, ...,
         5.86859737e-05, 5.86879490e-05, 5.86859751e-05]),
  59: array([3.09216341e-05, 3.98057692e-05, 3.96971062e-05, ...,
         5.86859741e-05, 5.86879491e-05, 5.86859751e-05]),
  60: array([3.36765151e-05, 4.35753802e-05, 4.30809289e-05, ...,
         5.86859745e-05, 5.86879492e-05, 5.86859752e-05]),
  61: array([3.64719209e-05, 4.74189898e-05, 4.64892688e-05, ...,
         5.86859749e-05, 5.86879493e-05, 5.86859752e-05]),
  62: array([3.92948618e-05, 5.13201230e-05, 4.99071577e-05, ...,
         5.86859753e-05, 5.86879494e-05, 5.86859752e-05]),
  63: array([4.21342967e-05, 5.52646162e-05, 5.33221459e-05, ...,
         5.86859757e-05, 5.86879495e-05, 5.86859752e-05]),
  64: array([4.49809098e-05, 5.92403205e-05, 5.67239520e-05, ...,
         5.86859760e-05, 5.86879496e-05, 5.86859753e-05]),
  65: array([4.78268859e-05, 6.32368205e-05, 6.01041390e-05, ...,
         5.86859764e-05, 5.86879497e-05, 5.86859753e-05]),
  66: array([5.06656989e-05, 6.72451807e-05, 6.34558259e-05, ...,
         5.86859768e-05, 5.86879498e-05, 5.86859753e-05]),
  67: array([5.34919222e-05, 7.12577257e-05, 6.67734386e-05, ...,
         5.86859772e-05, 5.86879499e-05, 5.86859753e-05]),
  68: array([5.63010626e-05, 7.52678517e-05, 7.00524977e-05, ...,
         5.86859776e-05, 5.86879500e-05, 5.86859754e-05]),
  69: array([5.90894164e-05, 7.92698678e-05, 7.32894392e-05, ...,
         5.86859779e-05, 5.86879501e-05, 5.86859754e-05]),
  70: array([6.18539475e-05, 8.32588624e-05, 7.64814651e-05, ...,
         5.86859783e-05, 5.86879502e-05, 5.86859754e-05]),
  71: array([6.45921833e-05, 8.72305919e-05, 7.96264175e-05, ...,
         5.86859787e-05, 5.86879503e-05, 5.86859754e-05]),
  72: array([6.73021276e-05, 9.11813871e-05, 8.27226746e-05, ...,
         5.86859791e-05, 5.86879504e-05, 5.86859755e-05]),
  73: array([6.99821865e-05, 9.51080754e-05, 8.57690628e-05, ...,
         5.86859795e-05, 5.86879505e-05, 5.86859755e-05]),
  74: array([7.26311059e-05, 9.90079146e-05, 8.87647840e-05, ...,
         5.86859798e-05, 5.86879506e-05, 5.86859755e-05])},
 'list_H': array([ 0.66731384,  0.66545478,  0.66353751,  0.66155599,  0.6595032 ,
         0.65737098,  0.6551498 ,  0.65282839,  0.65039343,  0.64782897,
         0.64511584,  0.6422308 ,  0.6391455 ,  0.63582507,  0.63222619,
         0.62829453,  0.62396107,  0.61913684,  0.61370505,  0.60750906,
         0.60033328,  0.59187146,  0.58167159,  0.56903408,  0.5528098 ,
         0.53096684,  0.4996668 ,  0.45307926,  0.40175806,  0.38125315,
         0.35479226,  0.36779086,  0.36106657,  0.35356614,  0.34513404,
         0.33562409,  0.3248885 ,  0.31278341,  0.29918213,  0.28399496,
         0.26719402,  0.2488382 ,  0.22908986,  0.20821413,  0.18655572,
         0.16449799,  0.14241685,  0.12064292,  0.09943991,  0.07899902,
         0.05944468,  0.04084609,  0.02323005,  0.00659282, -0.00909016,
        -0.02385676, -0.03775272, -0.0508277 , -0.06313263, -0.07471797,
        -0.08563253, -0.09592286, -0.10563281, -0.11480343, -0.12347287,
        -0.13167655, -0.13944717, -0.14681492, -0.15380762, -0.16045093]),
 'list_H_intercept': array([-15.0200724 , -15.00378784, -14.98700973, -14.96969149,
        -14.95177949, -14.93321165, -14.91391564, -14.89380659,
        -14.87278419, -14.85072903, -14.82749797, -14.80291811,
        -14.77677901, -14.74882245, -14.71872856, -14.68609694,
        -14.65041992, -14.61104416, -14.56711345, -14.5174811 ,
        -14.46057075, -14.39414567, -14.3149075 , -14.21775529,
        -14.09431538, -13.92978805, -13.69622505, -13.35119239,
        -12.97154716, -12.81591727, -12.61598027, -12.70426523,
        -12.64805555, -12.58588794, -12.51661438, -12.43915653,
        -12.35242731, -12.2553731 , -12.14707223, -12.02688205,
        -11.89462185, -11.7507562 , -11.59651707, -11.43389624,
        -11.26547312, -11.09411155, -10.92261841, -10.75346445,
        -10.58862381, -10.42953234, -10.2771298 , -10.13194451,
         -9.99418843,  -9.86384469,  -9.74073969,  -9.62459876,
         -9.51508716,  -9.41183912,  -9.3144779 ,  -9.22262911,
         -9.13592931,  -9.05403124,  -8.97660673,  -8.90334806,
         -8.83396825,  -8.76820072,  -8.7057985 ,  -8.64653319,
         -8.59019384,  -8.53658573]),
 'tau': array([-3.00194153, -2.92981885, -2.85790504, -2.78620118, -2.71470832,
        -2.64342746, -2.57235951, -2.5015053 , -2.43086555, -2.36044084,
        -2.29023167, -2.22023851, -2.15046191, -2.08090262, -2.0115619 ,
        -1.94244179, -1.8735455 , -1.80487789, -1.73644606, -1.66825997,
        -1.60033328, -1.53268432, -1.46533727, -1.39832385, -1.33168588,
        -1.26548342, -1.19986672, -1.13592378, -1.08035161, -1.03812531,
        -1.        , -0.96322091, -0.92778669, -0.89393016, -0.86194638,
        -0.83218795, -0.8050669 , -0.78105161, -0.7606543 , -0.74440453,
        -0.73280598, -0.72627798, -0.72509216, -0.72932162, -0.73882199,
        -0.75325301, -0.77213304, -0.79490703, -0.82100815, -0.84990186,
        -0.88111063, -0.91422322, -0.9488939 , -0.98483652, -1.02181637,
        -1.0596419 , -1.09815708, -1.13723478, -1.17677136, -1.2166821 ,
        -1.2568976 , -1.29736087, -1.33802501, -1.37885131, -1.41980777,
        -1.46086792, -1.5020098 , -1.54321519, -1.58446897, -1.62575862]),
 'alpha': array([ 0.72122681,  0.71913811,  0.71703857,  0.71492857,  0.71280863,
         0.71067948,  0.70854208,  0.70639757,  0.70424711,  0.70209165,
         0.69993155,  0.6977661 ,  0.69559289,  0.69340718,  0.69120111,
         0.68896291,  0.68667605,  0.68431835,  0.68186091,  0.67926686,
         0.67648963,  0.67347044,  0.67013418,  0.66637976,  0.66202457,
         0.65616701,  0.63942942,  0.55572166,  0.42226298,  0.38125315,
         0.36779086,  0.35434227,  0.33856529,  0.31983775,  0.2975843 ,
         0.27121054,  0.24015289,  0.20397315,  0.16249762,  0.11598559,
         0.0652799 ,  0.01185821, -0.04229461, -0.0950037 , -0.14431014,
        -0.18880031, -0.22773994, -0.2610112 , -0.28893708, -0.31208773,
        -0.33112582, -0.34670683, -0.3594262 , -0.36979854, -0.37825531,
        -0.38515172, -0.39077708, -0.3953658 , -0.39910736, -0.40215497,
        -0.40463272, -0.40664136, -0.40826298, -0.40956468, -0.4106015 ,
        -0.41141876, -0.41205387, -0.41253787, -0.41289651]),
 'mfSpect': array([0.83826109, 0.84431834, 0.85019704, 0.85589403, 0.86140588,
        0.86672876, 0.87185852, 0.87679089, 0.8815219 , 0.88604837,
        0.89036856, 0.89448293, 0.89839471, 0.90211041, 0.90564012,
        0.90899743, 0.91219902, 0.91526404, 0.91821296, 0.92106642,
        0.92384365, 0.92656092, 0.92922993, 0.93185803, 0.93447114,
        0.93739992, 0.94409495, 0.96920728, 0.99589902, 1.        ,
        1.        , 0.99865514, 0.99549974, 0.98988148, 0.9809801 ,
        0.96779322, 0.94915863, 0.92383282, 0.89065239, 0.84879156,
        0.79808588, 0.73932202, 0.67433863, 0.60581682, 0.5367878 ,
        0.47005254, 0.40774914, 0.351188  , 0.3009214 , 0.25693518,
        0.21885899, 0.18613888, 0.15815626, 0.13429988, 0.11400362,
        0.09676262, 0.08213666, 0.06974711, 0.05927074, 0.05043268,
        0.04299944, 0.03677265, 0.03158345, 0.02728785, 0.02376266,
        0.02090228, 0.01861586, 0.01682509, 0.01546222])}

In [33]:
df['tick']['median_traded_volume'] - df1['tick']['median_traded_volume']

0       0.0
1       0.0
2       0.0
3       0.0
4       0.0
       ...
1352    NaN
1353    NaN
1354    NaN
1355    NaN
1356    NaN
Name: TradedVolume_median, Length: 1357, dtype: float64

In [20]:
# Create an instance of VolatilityCalculator
calculator = VolatilityCalculator(rolling_window=5)

# Apply the functions on the DataFrame
df = calculator.garman_klass_parkinson_vols(df)
df = calculator.calculate_midquote_returns(df)
df = calculator.compute_spreads(df)

# Print the updated DataFrame
print(df)

              time_first            time_max            time_min  \
0    2018-05-16 00:00:00 2018-05-16 00:00:10 2018-05-16 00:00:00
1    2018-05-16 00:00:11 2018-05-16 00:00:15 2018-05-16 00:00:11
2    2018-05-16 00:00:16 2018-05-16 00:00:25 2018-05-16 00:00:16
3    2018-05-16 00:00:26 2018-05-16 00:00:35 2018-05-16 00:00:26
4    2018-05-16 00:00:36 2018-05-16 00:00:49 2018-05-16 00:00:36
...                  ...                 ...                 ...
5654 2018-05-16 23:53:12 2018-05-16 23:53:57 2018-05-16 23:53:12
5655 2018-05-16 23:53:59 2018-05-16 23:55:53 2018-05-16 23:53:59
5656 2018-05-16 23:55:54 2018-05-16 23:57:57 2018-05-16 23:55:54
5657 2018-05-16 23:57:57 2018-05-16 23:59:01 2018-05-16 23:57:57
5658 2018-05-16 23:59:01 2018-05-16 23:59:58 2018-05-16 23:59:01

               time_last     time_<lambda_0>  BestBid_median  BestAsk_median  \
0    2018-05-16 00:00:10 2018-05-16 00:00:00          97.095          97.100
1    2018-05-16 00:00:15 2018-05-16 00:00:11          97.095          97.100
2    2018-05-16 00:00:25 2018-05-16 00:00:16          97.095          97.100
3    2018-05-16 00:00:35 2018-05-16 00:00:26          97.095          97.100
4    2018-05-16 00:00:49 2018-05-16 00:00:36          97.095          97.100
...                  ...                 ...             ...             ...
5654 2018-05-16 23:53:57 2018-05-16 23:53:12          97.090          97.095
5655 2018-05-16 23:55:53 2018-05-16 23:53:59          97.090          97.095
5656 2018-05-16 23:57:57 2018-05-16 23:55:54          97.090          97.095
5657 2018-05-16 23:59:01 2018-05-16 23:57:57          97.090          97.095
5658 2018-05-16 23:59:58 2018-05-16 23:59:01          97.090          97.095

      MicroPrice_median  arrival_rate_median  MeanRelativeTickVolume_median  \
0             97.098866             0.000012                            0.0
1             97.099055             0.000012                            0.0
2             97.098226             0.000012                            0.0
3             97.098935             0.000012                            0.0
4             97.099188             0.000012                            0.0
...                 ...                  ...                            ...
5654          97.091977             0.000012                            0.0
5655          97.091998             0.000012                            0.0
5656          97.091983             0.000012                            0.0
5657          97.091905             0.000012                            0.0
5658          97.091912             0.000012                            0.0

      ...        log_hl        log_cc  garman_klass_vol  log_hl_squared  \
0     ...  2.412695e-05  6.575406e-06      1.656360e-05    5.821096e-10
1     ...  1.668964e-05 -1.228520e-05      8.998343e-06    2.785441e-10
2     ...  3.305396e-05  1.152133e-05      2.224871e-05    1.092564e-09
3     ...  1.196927e-05  9.263869e-08      8.463358e-06    1.432635e-10
4     ...  1.302846e-05  7.136465e-06      8.074448e-06    1.697407e-10
...   ...           ...           ...               ...             ...
5654  ...  5.338218e-09  5.338218e-09      1.800061e-09    2.849657e-17
5655  ...  0.000000e+00  0.000000e+00      0.000000e+00    0.000000e+00
5656  ...  8.496734e-06  8.496734e-06      2.865121e-06    7.219449e-11
5657  ...  0.000000e+00  0.000000e+00      0.000000e+00    0.000000e+00
5658  ...  1.782397e-05  7.765177e-07      1.259420e-05    3.176938e-10

      parkinson_vol  bipower_var          MQSR          MQAR  EffectiveSpread  \
0           0.00001          NaN           NaN           NaN         0.539417
1           0.00001          NaN  6.726982e-12  2.593643e-06         0.215767
2           0.00001          NaN  7.009193e-11  8.372092e-06         0.485475
3           0.00001          NaN  9.042185e-11  9.509040e-06         0.485475
4           0.00001          NaN  4.595028e-13  6.778663e-07         0.701242
...             ...          ...           ...           ...              ...
5654        0.00001          0.0  2.493674e-10  1.579137e-05         0.323633
5655        0.00001          0.0  2.331874e-10  1.527047e-05         0.000000
5656        0.00001          0.0  1.811859e-11  4.256593e-06         0.107878
5657        0.00001          0.0  1.855380e-11  4.307412e-06         0.000000
5658        0.00001          0.0  2.785973e-10  1.669123e-05         0.431511

      RealizedSpread
0           0.539444
1           0.215756
2           0.485475
3           0.485475
4           0.701242
...              ...
5654             NaN
5655             NaN
5656             NaN
5657             NaN
5658             NaN

[5659 rows x 70 columns]

In [9]:
# import pandas as pd

# def compute_spreads(df: pd.DataFrame) -> pd.DataFrame:
#     bid_plus_offer = df['BASpread_median']
#     bid_plus_offer_shifted = (df['BASpread_median'].shift(-100) + df['BASpread_median'].shift(-100)) / 2
#     dt = pd.to_timedelta(df['time_close'] - df['time_open']).dt.total_seconds() / 3600

#     effective_spread = 2 * dt * (df['TradePrice_median'] - bid_plus_offer)
#     realized_spread = 2 * dt * (df['TradePrice_median'] - bid_plus_offer_shifted)

#     spreads_df = pd.DataFrame({
#         'EffectiveSpread': effective_spread,
#         'RealizedSpread': realized_spread
#     })

#     # Compute the lower and upper percentiles
#     lower_percentile = np.percentile(spreads_df.values, 10)
#     upper_percentile = np.percentile(spreads_df.values, 90)

#     # Replace extreme values with the median
#     spreads_df = np.where((spreads_df < lower_percentile) | (spreads_df > upper_percentile),
#                           np.median(spreads_df[(spreads_df >= lower_percentile) & (spreads_df <= upper_percentile)]),
#                           spreads_df)

#     df[['EffectiveSpread', 'RealizedSpread']] = spreads_df

#     return df

# def calculate_midquote_returns(df: pd.DataFrame) -> pd.DataFrame:
#     midquote = (df['MicroPrice_high'] + df['MicroPrice_low']) / 2

#     mqsr = np.square(np.log(midquote) - np.log(midquote.shift(1)))
#     mqar = np.abs(np.log(midquote) - np.log(midquote.shift(1)))

#     df['MQSR'] = mqsr
#     df['MQAR'] = mqar

#     return df

In [13]:
calculate_midquote_returns(compute_spreads(testdf))

,time_first,time_max,time_min,time_last,time_<lambda_0>,BestBid_median,BestAsk_median,MicroPrice_median,arrival_rate_median,MeanRelativeTickVolume_median,...,MeanRelativeTickVolume_low,MeanRelativeTickVolume_close,OrderImbalance_open,OrderImbalance_high,OrderImbalance_low,OrderImbalance_close,EffectiveSpread,RealizedSpread,MQSR,MQAR
0,2018-05-16 00:00:00,2018-05-16 00:00:10,2018-05-16 00:00:00,2018-05-16 00:00:10,2018-05-16 00:00:00,97.095,97.100,97.098866,0.000012,0.0,...,0.0,0.0,0.546358,0.852912,-0.084164,0.801744,0.539417,0.539444,NaN,NaN
1,2018-05-16 00:00:11,2018-05-16 00:00:15,2018-05-16 00:00:11,2018-05-16 00:00:15,2018-05-16 00:00:11,97.095,97.100,97.099055,0.000012,0.0,...,0.0,0.0,0.638151,0.809218,0.161001,0.161001,0.215767,0.215756,6.726982e-12,2.593643e-06
2,2018-05-16 00:00:16,2018-05-16 00:00:25,2018-05-16 00:00:16,2018-05-16 00:00:25,2018-05-16 00:00:16,97.095,97.100,97.098226,0.000012,0.0,...,0.0,0.0,0.354354,0.801837,-0.481951,0.801837,0.485475,0.485475,7.009193e-11,8.372092e-06
3,2018-05-16 00:00:26,2018-05-16 00:00:35,2018-05-16 00:00:26,2018-05-16 00:00:35,2018-05-16 00:00:26,97.095,97.100,97.098935,0.000012,0.0,...,0.0,0.0,0.758110,0.761708,0.296827,0.761708,0.485475,0.485475,9.042185e-11,9.509040e-06
4,2018-05-16 00:00:36,2018-05-16 00:00:49,2018-05-16 00:00:36,2018-05-16 00:00:49,2018-05-16 00:00:36,97.095,97.100,97.099188,0.000012,0.0,...,0.0,0.0,0.302586,0.808606,0.302586,0.579763,0.701242,0.701242,4.595028e-13,6.778663e-07
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5654,2018-05-16 23:53:12,2018-05-16 23:53:57,2018-05-16 23:53:12,2018-05-16 23:53:57,2018-05-16 23:53:12,97.090,97.095,97.091977,0.000012,0.0,...,0.0,0.0,0.591454,0.591661,0.591454,0.591661,0.323633,NaN,2.493674e-10,1.579137e-05
5655,2018-05-16 23:53:59,2018-05-16 23:55:53,2018-05-16 23:53:59,2018-05-16 23:55:53,2018-05-16 23:53:59,97.090,97.095,97.091998,0.000012,0.0,...,0.0,0.0,-0.001598,-0.001598,-0.001598,-0.001598,0.000000,NaN,2.331874e-10,1.527047e-05
5656,2018-05-16 23:55:54,2018-05-16 23:57:57,2018-05-16 23:55:54,2018-05-16 23:57:57,2018-05-16 23:55:54,97.090,97.095,97.091983,0.000012,0.0,...,0.0,0.0,-0.001279,0.328761,-0.001279,0.328761,0.107878,NaN,1.811859e-11,4.256593e-06
5657,2018-05-16 23:57:57,2018-05-16 23:59:01,2018-05-16 23:57:57,2018-05-16 23:59:01,2018-05-16 23:57:57,97.090,97.095,97.091905,0.000012,0.0,...,0.0,0.0,0.331055,0.331055,0.331055,0.331055,0.000000,NaN,1.855380e-11,4.307412e-06
5658,2018-05-16 23:59:01,2018-05-16 23:59:58,2018-05-16 23:59:01,2018-05-16 23:59:58,2018-05-16 23:59:01,97.090,97.095,97.091912,0.000012,0.0,...,0.0,0.0,-0.001280,0.028883,-0.663448,0.028883,0.431511,NaN,2.785973e-10,1.669123e-05

In [ ]:
jumps = detect_jumps(returnSeries, 0.15)

In [ ]:
plt.plot(jumps.Jump)

In [ ]:
df =testdf
def garman_klass_parkinson_vols(df, rolling_window: int = 5):
    df['log_hl'] = (df['MicroPrice_high'] / df['MicroPrice_low']).replace([np.inf, -np.inf], np.nan).apply(np.log).fillna(0)
    df['log_cc'] = (df['MicroPrice_close'] / df['MicroPrice_open']).replace([np.inf, -np.inf], np.nan).apply(np.log).fillna(0)
    df['garman_klass_vol'] = np.sqrt(0.5 * df['log_hl']**2 - (2*np.log(2) - 1) * df['log_cc']**2) 
    df['log_hl_squared'] = np.log(df['MicroPrice_high'] / df['MicroPrice_low'])**2
    df['parkinson_vol'] = np.sqrt((1 / (4 * np.log(2))) * df['log_hl_squared'].mean())
    df['bipower_var'] = (np.abs(df['log_hl']) * np.abs(df['log_hl'].shift(1))).rolling(rolling_window).sum()
    return df

In [ ]:
import numpy as np

def parkinson_vol(df):
    df['log_hl_squared'] = np.log(df['MicroPrice_high'] / df['MicroPrice_low'])**2
    df['parkinson_vol'] = np.sqrt((1 / (4 * np.log(2))) * df['log_hl_squared'].mean())
    return df

In [ ]:
df =garman_klass_parkinson_vols(testdf)

In [ ]:
compute_spreads(df).columns.values

In [ ]:
compute_spreads(df).describe()

In [ ]:
plt.plot(df.bipower_var)

In [ ]:
# Add Garman-Klass volatility calculation
# Replace 'TradePrice_close' and 'TradePrice_open' with the actual column names you want to use in your DataFrame
resampled_df['period'] = (pd.to_datetime(resampled_df['time_last']) - pd.to_datetime(resampled_df['time_first'])).dt.total_seconds() / (24 * 60 * 60)
resampled_df['log_hl'] = np.where((resampled_df['BestBid_high'] != resampled_df['BestBid_low']), np.log(resampled_df['BestBid_high'] / resampled_df['BestBid_low']), 0)
resampled_df['log_cc'] = np.where((resampled_df['TradePrice_close'] != resampled_df['TradePrice_open']), np.log(resampled_df['TradePrice_close'] / resampled_df['TradePrice_open']), 0)
resampled_df['garman_klass_vol'] = np.sqrt(0.5 * resampled_df['log_hl']**2 - (2*np.log(2) - 1) * resampled_df['log_cc']**2)

In [ ]:
_=plt.plot(df.garman_klass_vol)

In [ ]:
import numpy as np
import pandas as pd



def garman_klass(df, clean=True):
    df.fillna(value=mean_value, inplace=True)
    df['period'] = (pd.to_datetime(df['time_close']) - pd.to_datetime(df['time_open'])).dt.total_seconds() / (24 * 60 * 60)
    df['log_hl'] = (df['MicroPrice_high'] / df['MicroPrice_low']).replace([np.inf, -np.inf], np.nan).apply(np.log).fillna(0)
    df['log_cc'] = (df['MicroPrice_close'] / df['MicroPrice_open']).replace([np.inf, -np.inf], np.nan).apply(np.log).fillna(0)
    df['garman_klass_vol'] = np.sqrt(0.5 * df['log_hl']**2 - (2*np.log(2) - 1) * df['log_cc']**2) / np.sqrt(df['period']).replace([np.inf, -np.inf], np.nan).fillna(0)
#     if clean:
#         df = df.dropna()
    return df


# # Use the function on your DataFrame
# df = garman_klass(df)

In [ ]:
testdf.columns

In [ ]:
_=plt.hist((testdf['OrderImbalance_open']+testdf['OrderImbalance_close']/2), bins =200)

In [ ]:
# Create an instance of VolatilityMetrics
metrics = VolatilityMetrics()

In [ ]:
# Function: parkinson
dataframe = testdf
parkinson_df = metrics.parkinson(dataframe)
print("Parkinson DataFrame:\n", parkinson_df)

In [39]:
## testing

In [40]:
import os
import pandas as pd
import numpy as np

In [41]:
t7folder ='/media/ak/T7/FuturesDataSemiProcessed/RX1'

In [42]:
files = os.listdir(t7folder)

In [44]:
file = os.path.join(t7folder, files[10])

In [46]:
testFileDict =pd.read_pickle(file)

In [47]:
testFileDict.keys()

dict_keys(['20180529'])

In [50]:
testFileDict['20180529']['tick']

,BidSize_open,BidSize_high,BidSize_low,BidSize_close,QuoteTime_open,QuoteTime_high,QuoteTime_low,QuoteTime_close,type_x_open,type_x_high,...,dollar_traded_volume_low,dollar_traded_volume_close,timeStampIdx_open,timeStampIdx_high,timeStampIdx_low,timeStampIdx_close,micro_price_open,micro_price_high,micro_price_low,micro_price_close
tick_bucket,,,,,,,,,,,,,,,,,,,,,
1.0,5,632,1,159,2018-05-04 06:01:14.943,2018-05-04 06:01:28.749,2018-05-04 06:01:14.943,2018-05-04 06:01:28.749,BID,BID,...,159.17,795.90,2018-05-04 06:01:14.850,2018-05-04 06:01:28.749,2018-05-04 06:01:14.850,2018-05-04 06:01:28.749,159.179675,159.189866,159.160342,159.172050
2.0,54,656,1,656,2018-05-04 06:01:28.939,2018-05-04 06:02:01.878,2018-05-04 06:01:28.939,2018-05-04 06:02:01.878,BID,BID,...,159.15,159.15,2018-05-04 06:01:28.939,2018-05-04 06:02:01.149,2018-05-04 06:01:28.939,2018-05-04 06:02:01.149,159.170000,159.179820,159.150017,159.155297
3.0,229,655,32,57,2018-05-04 06:02:01.924,2018-05-04 06:03:04.319,2018-05-04 06:02:01.924,2018-05-04 06:03:04.319,BID,BID,...,159.15,159.17,2018-05-04 06:02:01.924,2018-05-04 06:03:04.021,2018-05-04 06:02:01.924,2018-05-04 06:03:04.021,159.157696,159.169371,159.151463,159.167585
4.0,51,358,2,18,2018-05-04 06:03:04.329,2018-05-04 06:04:06.250,2018-05-04 06:03:04.329,2018-05-04 06:04:06.250,BID,BID,...,159.15,318.32,2018-05-04 06:03:04.021,2018-05-04 06:04:06.250,2018-05-04 06:03:04.021,2018-05-04 06:04:06.250,159.167783,159.169934,159.150083,159.169477
5.0,20,60,2,55,2018-05-04 06:04:06.250,2018-05-04 06:04:23.257,2018-05-04 06:04:06.250,2018-05-04 06:04:23.257,BID,BID,...,159.17,159.17,2018-05-04 06:04:06.250,2018-05-04 06:04:23.079,2018-05-04 06:04:06.250,2018-05-04 06:04:23.079,159.169422,159.169936,159.168165,159.168292
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10257.0,14,37,1,11,2018-05-29 19:53:23.473,2018-05-29 19:54:47.882,2018-05-29 19:53:23.473,2018-05-29 19:54:47.882,BID,BID,...,163.38,326.82,2018-05-29 19:53:23.473,2018-05-29 19:54:47.882,2018-05-29 19:53:23.473,2018-05-29 19:54:47.882,163.384167,163.414500,163.371111,163.414500
10258.0,12,37,1,2,2018-05-29 19:54:47.882,2018-05-29 19:55:05.383,2018-05-29 19:54:47.882,2018-05-29 19:55:05.383,BID,BID,...,163.40,326.80,2018-05-29 19:54:47.882,2018-05-29 19:55:04.721,2018-05-29 19:54:47.882,2018-05-29 19:55:04.721,163.414286,163.427755,163.390476,163.408571
10259.0,3,26,1,12,2018-05-29 19:55:05.385,2018-05-29 19:56:31.867,2018-05-29 19:55:05.385,2018-05-29 19:56:31.867,BID,BID,...,163.39,326.78,2018-05-29 19:55:04.721,2018-05-29 19:56:31.867,2018-05-29 19:55:04.721,2018-05-29 19:56:31.867,163.408000,163.409231,163.381111,163.390769
10260.0,13,19,1,7,2018-05-29 19:56:31.868,2018-05-29 19:57:56.432,2018-05-29 19:56:31.868,2018-05-29 19:57:56.432,BID,BID,...,163.39,490.17,2018-05-29 19:56:31.867,2018-05-29 19:57:56.432,2018-05-29 19:56:31.867,2018-05-29 19:57:56.432,163.390714,163.428889,163.382308,163.383000
10261.0,6,38,1,24,2018-05-29 19:57:56.432,2018-05-29 19:58:28.336,2018-05-29 19:57:56.432,2018-05-29 19:58:28.336,BID,BID,...,163.34,163.37,2018-05-29 19:57:56.432,2018-05-29 19:58:28.335,2018-05-29 19:57:56.432,2018-05-29 19:58:28.335,163.383333,163.389091,163.330769,163.358824

In [51]:
## raw data testing

In [52]:
rawdatafolder = '/media/ak/Data/raw bloomberg data/'

In [60]:
import os

def get_subfolder_lengths(folder_path):
    for root, dirs, files in os.walk(folder_path):
        if root != folder_path:  # Exclude the main folder
            subfolder_name = os.path.basename(root)
            subfolder_length = len(dirs) + len(files)
            print(f"Subfolder '{subfolder_name}': {subfolder_length} items")

# Provide the path to the folder you want to analyze
folder_path = "/path/to/folder"

get_subfolder_lengths(rawdatafolder)

Subfolder 'DU1_Comdty-20181028': 139 items
Subfolder 'FB1_Comdty-20181028': 139 items
Subfolder 'FV1_Comdty-20181028': 141 items
Subfolder 'G_1_Comdty-20181028': 136 items
Subfolder 'JB1_Comdty-20181028': 140 items
Subfolder 'KE1_Comdty-20181028': 139 items
Subfolder 'OE1_Comdty-20181028': 139 items
Subfolder 'RX1_Comdty-20181028': 139 items
Subfolder 'VIX_Index-20181027': 137 items

In [57]:
file = os.path.join(rawdatafolder, 'G_1_Comdty-20181028','G_1_Comdty-20180417.csv' )

In [80]:
dfTest =pd.read_csv(file)

In [83]:
trades = dfTest[dfTest['type']=='TRADE']
quotes = dfTest[dfTest['type']!='TRADE']

In [84]:
quotes

        Unnamed: 0  size                     time type   value
63              63     4  2018-04-17 07:00:00.279  BID  121.81
64              64     6  2018-04-17 07:00:00.279  ASK  121.82
67              67     8  2018-04-17 07:00:00.302  BID  121.79
68              68    11  2018-04-17 07:00:00.302  ASK  121.81
69              69    12  2018-04-17 07:00:00.330  ASK  121.81
...            ...   ...                      ...  ...     ...
163639      163639   198  2018-04-17 17:00:00.058  BID  122.09
163640      163640     0  2018-04-17 17:00:00.270  BID    0.00
163641      163641     0  2018-04-17 17:00:00.270  ASK    0.00
163642      163642     0  2018-04-17 17:00:00.000  BID  122.09
163643      163643     0  2018-04-17 17:00:00.000  ASK  122.12

[101617 rows x 5 columns]

In [65]:
irf = '/media/ak/Data/InterestRateFuturesData'
quotesTrades = os.path.join(irf, 'QuotesTrades'

In [79]:
# columns need to be like : ['Unnamed: 0', 'size', 'time', 'type', 'value']

array(['Unnamed: 0', 'size', 'time', 'type', 'value'], dtype=object)

In [86]:
os.listdir(quotesTrades)

['DU1', 'FB1', 'G_1', 'RX1', 'SI1', 'TY1', 'US1', 'UST2y', 'VXX', 'XM1', 'YM1']

In [87]:
string = '/media/ak/Data/raw bloomberg data/RX1_Comdty-20181028'

In [94]:
string.split("/")[-1].split("-")[0].split("_")[0]

'RX1'

In [97]:
pd.read_csv('/media/ak/Data/InterestRateFuturesData/QuotesTrades/JB1/JB1_Comdty_trades/20180821.csv')

      size                 time   type   value
0        1  2018-08-21 00:00:20  Trade  150.52
1        1  2018-08-21 00:00:21  Trade  150.52
2        2  2018-08-21 00:00:26  Trade  150.53
3        1  2018-08-21 00:00:34  Trade  150.52
4        1  2018-08-21 00:00:34  Trade  150.52
...    ...                  ...    ...     ...
3492     1  2018-08-21 23:59:51  Trade  150.51
3493    40  2018-08-21 23:59:57  Trade  150.51
3494    50  2018-08-21 23:59:57  Trade  150.51
3495    15  2018-08-21 23:59:57  Trade  150.51
3496     7  2018-08-22 00:00:00  Trade  150.51

[3497 rows x 4 columns]

In [104]:



get_subfolder_lengths('/media/ak/Data/InterestRateFuturesData/QuotesTrades')

Subfolder 'DU1': 2 items
Subfolder 'DU1_Comdty_quotes': 140 items
Subfolder 'DU1_Comdty_trades': 140 items
Subfolder 'FB1': 2 items
Subfolder 'FB1_Comdty_quotes': 136 items
Subfolder 'FB1_Comdty_trades': 139 items
Subfolder 'FV1': 2 items
Subfolder 'FV1_Comdty_quotes': 141 items
Subfolder 'FV1_Comdty_trades': 141 items
Subfolder 'G': 2 items
Subfolder 'G_Comdty_quotes': 136 items
Subfolder 'G_Comdty_trades': 136 items
Subfolder 'JB1': 2 items
Subfolder 'JB1_Comdty_quotes': 140 items
Subfolder 'JB1_Comdty_trades': 140 items
Subfolder 'KE1': 2 items
Subfolder 'KE1_Comdty_quotes': 139 items
Subfolder 'KE1_Comdty_trades': 139 items
Subfolder 'OE1': 2 items
Subfolder 'OE1_Comdty_quotes': 139 items
Subfolder 'OE1_Comdty_trades': 139 items
Subfolder 'RX1': 2 items
Subfolder 'RX1_Comdty_quotes': 139 items
Subfolder 'RX1_Comdty_trades': 139 items
Subfolder 'SI1': 1 items
Subfolder 'SI1_Comdty_Trades': 141 items
Subfolder 'TY1': 2 items
Subfolder 'TY1_Comdty_quotes': 108 items
Subfolder 'TY1_Comdty_trades': 108 items
Subfolder 'US1': 2 items
Subfolder 'US1_Comdty_quotes': 141 items
Subfolder 'US1_Comdty_trades': 141 items
Subfolder 'UST2y': 2 items
Subfolder 'UST2y_Comdty_quotes': 139 items
Subfolder 'UST2y_Comdty_trades': 139 items
Subfolder 'VXX': 3 items
Subfolder 'VXX_US_Equity': 126 items
Subfolder 'VXX_US_Equity_quotes': 126 items
Subfolder 'VXX_US_Equity_trades': 126 items
Subfolder 'XM1': 2 items
Subfolder 'XM1_Comdty_quotes': 140 items
Subfolder 'XM1_Comdty_trades': 140 items
Subfolder 'YM1': 2 items
Subfolder 'YM1_Comdty_quotes': 141 items
Subfolder 'YM1_Comdty_trades': 141 items

In [121]:
folder = '/media/ak/Data/InterestRateFuturesData/ReconstructedLOB/FV1'
files = os.listdir('/media/ak/Data/InterestRateFuturesData/ReconstructedLOB/FV1')

In [122]:
testFile = os.path.join(folder, files[15])
df =pd.read_pickle(testFile)

In [123]:
df.shape

(72814, 30)

In [124]:
df.tail(10)

,time,estimated_arrival_time,TradePrice,TradedVolume,NoOfTrades,arrival_rate,AverageVolumePerTrade,date,CCYTradedVolume,type,...,RunningNoOfTrades,RunningCumlVolume,RunningCumlNoOfTrades,MicroPrice,BASpread,QuoteSize,MidPrice,OrderImbalance,ExpandingMeanRelativeTickVolume,MeanRelativeTickVolume
3970876,2018-05-02 23:56:07,1726-01-22 00:07:47.145224192,113.4375,1.0,1.0,0.000012,1.0,2018-05-02,113.4375,BID,...,1.0,8.206333e+07,30077.0,113.438426,0.007812,3078.0,113.441406,-0.762833,0.00000,0.000000
3937944,2018-05-02 23:56:27,1726-01-22 00:07:47.145224192,113.4375,1.0,1.0,0.000012,1.0,2018-05-02,113.4375,ASK,...,1.0,8.206333e+07,30077.0,113.441322,0.007812,746.0,113.441406,-0.021448,0.00000,0.000000
3970877,2018-05-02 23:57:49,1726-01-22 00:07:47.145224192,113.4375,1.0,1.0,0.000012,1.0,2018-05-02,113.4375,BID,...,1.0,8.206333e+07,30077.0,113.441312,0.007812,744.0,113.441406,-0.024194,0.00000,0.000000
3937945,2018-05-02 23:57:49,1726-01-22 00:07:47.145224192,113.4375,1.0,1.0,0.000012,1.0,2018-05-02,113.4375,ASK,...,1.0,8.206333e+07,30077.0,113.442985,0.007812,517.0,113.441406,0.404255,0.00000,0.000000
445147,2018-05-02 23:57:49,1726-01-22 00:10:32.145224192,113.4375,2.0,1.0,0.000012,2.0,2018-05-02,226.8750,Trade,...,1.0,8.206356e+07,30078.0,113.442985,0.007812,517.0,113.441406,0.404255,0.20119,0.201204
3937946,2018-05-02 23:58:59,1726-01-22 00:10:32.145224192,113.4375,2.0,1.0,0.000012,2.0,2018-05-02,226.8750,ASK,...,1.0,8.206356e+07,30078.0,113.442943,0.007812,521.0,113.441406,0.393474,0.00000,0.000000
3937947,2018-05-02 23:59:14,1726-01-22 00:10:32.145224192,113.4375,2.0,1.0,0.000012,2.0,2018-05-02,226.8750,ASK,...,1.0,8.206356e+07,30078.0,113.441586,0.007812,694.0,113.441406,0.046110,0.00000,0.000000
3937948,2018-05-02 23:59:25,1726-01-22 00:10:32.145224192,113.4375,2.0,1.0,0.000012,2.0,2018-05-02,226.8750,ASK,...,1.0,8.206356e+07,30078.0,113.442831,0.007812,532.0,113.441406,0.364662,0.00000,0.000000
3937949,2018-05-02 23:59:29,1726-01-22 00:10:32.145224192,113.4375,2.0,1.0,0.000012,2.0,2018-05-02,226.8750,ASK,...,1.0,8.206356e+07,30078.0,113.439653,0.007812,1317.0,113.441406,-0.448747,0.00000,0.000000
3937950,2018-05-02 23:59:30,1726-01-22 00:10:32.145224192,113.4375,2.0,1.0,0.000012,2.0,2018-05-02,226.8750,ASK,...,1.0,8.206356e+07,30078.0,113.440760,0.007812,870.0,113.441406,-0.165517,0.00000,0.000000

In [129]:
import os

def get_unique_elements(directory, subdirectory1, subdirectory2):
    path1 = os.path.join(directory, subdirectory1)
    path2 = os.path.join(directory, subdirectory2)
    
    if not os.path.isdir(path1) or not os.path.isdir(path2):
        print("Error: One or both subdirectories do not exist.")
        return []
    
    elements1 = set(os.listdir(path1))
    elements2 = set(os.listdir(path2))
    
    unique_elements = elements1.symmetric_difference(elements2)
    return unique_elements

# Usage example
directory = '/media/ak/Data/InterestRateFuturesData/QuotesTrades/KE1'
subdirectory1 = 'KE1_Comdty_quotes'
subdirectory2 = 'KE1_Comdty_trades'

unique_elements = get_unique_elements(directory, subdirectory1, subdirectory2)
print(unique_elements)

set()

In [130]:
import os

def create_subdirectories(main_directory, subdirectory_names):
    # Create the main directory if it doesn't exist
    if not os.path.exists(main_directory):
        os.makedirs(main_directory)

    # Create subdirectories within the main directory
    for name in subdirectory_names:
        subdirectory_path = os.path.join(main_directory, name)
        os.makedirs(subdirectory_path)
        print(f"Created subdirectory: {subdirectory_path}")

In [132]:
EventClocks ='/media/ak/Data/InterestRateFuturesData/EventClocksFiles'
os.listdir(EventClocks)

['DU1', 'FB1', 'FV1', 'JB1', 'KE1', 'OE1', 'RX1', 'US1', 'US2y', 'XM1', 'YM1']

In [134]:

# Example usage
main_directory = "/media/ak/Data/InterestRateFuturesData/MFDCCA"
subdirectory_names = ['DU1', 'FB1', 'FV1', 'JB1', 'KE1', 'OE1', 'RX1', 'TY1', 
                      'US1', 'UST2y', 'XM1', 'YM1', 'UST5y','UST10y',]

create_subdirectories(main_directory, subdirectory_names)

Created subdirectory: /media/ak/Data/InterestRateFuturesData/MFDCCA/DU1
Created subdirectory: /media/ak/Data/InterestRateFuturesData/MFDCCA/FB1
Created subdirectory: /media/ak/Data/InterestRateFuturesData/MFDCCA/FV1
Created subdirectory: /media/ak/Data/InterestRateFuturesData/MFDCCA/JB1
Created subdirectory: /media/ak/Data/InterestRateFuturesData/MFDCCA/KE1
Created subdirectory: /media/ak/Data/InterestRateFuturesData/MFDCCA/OE1
Created subdirectory: /media/ak/Data/InterestRateFuturesData/MFDCCA/RX1
Created subdirectory: /media/ak/Data/InterestRateFuturesData/MFDCCA/TY1
Created subdirectory: /media/ak/Data/InterestRateFuturesData/MFDCCA/US1
Created subdirectory: /media/ak/Data/InterestRateFuturesData/MFDCCA/UST2y
Created subdirectory: /media/ak/Data/InterestRateFuturesData/MFDCCA/XM1
Created subdirectory: /media/ak/Data/InterestRateFuturesData/MFDCCA/YM1
Created subdirectory: /media/ak/Data/InterestRateFuturesData/MFDCCA/UST5y
Created subdirectory: /media/ak/Data/InterestRateFuturesData/MFDCCA/UST10y

In [1]:
import os
import pandas as pd
import numpy as np

In [2]:
testDirt = '/media/ak/Data/ExperimentData/August11th2022Experiments/ExperimentInputFiles/outputs'

In [5]:
testFile = os.path.join(testDirt,  'G_1_tick_100_output.json')

In [20]:
testFiles = os.listdir(testDirt)
idx=10
testFileLoc = os.path.join(testDirt, testFiles[idx])

In [21]:
import json
  
# Opening JSON file
f = open(testFileLoc )
  
# returns JSON object as 
# a dictionary
data = json.load(f)

In [22]:
data.keys()

dict_keys(['n', 'rho', 'F', 'H', 'H_intercept'])

In [23]:
len(data['rho'])

50

In [24]:
pd.DataFrame.from_dict(data)

      n       rho         F         H  H_intercept
0    10  0.018321  0.000490  1.386677   -10.401392
1    30  0.004534  0.003324  1.386677   -10.401392
2    50 -0.014164  0.007008  1.386677   -10.401392
3    70 -0.019350  0.011619  1.386677   -10.401392
4    90 -0.048530  0.016096  1.386677   -10.401392
5   110 -0.064619  0.021372  1.386677   -10.401392
6   130 -0.044644  0.027905  1.386677   -10.401392
7   150 -0.046058  0.033730  1.386677   -10.401392
8   170 -0.071922  0.041117  1.386677   -10.401392
9   190 -0.104262  0.047559  1.386677   -10.401392
10  210 -0.133303  0.059247  1.386677   -10.401392
11  230 -0.158234  0.071929  1.386677   -10.401392
12  250 -0.011309  0.064086  1.386677   -10.401392
13  270 -0.072689  0.074173  1.386677   -10.401392
14  290 -0.152904  0.099232  1.386677   -10.401392
15  310 -0.163089  0.102988  1.386677   -10.401392
16  330 -0.155984  0.111800  1.386677   -10.401392
17  350 -0.110055  0.121274  1.386677   -10.401392
18  370  0.010548  0.105803  1.386677   -10.401392
19  390 -0.203817  0.122357  1.386677   -10.401392
20  410  0.035828  0.115721  1.386677   -10.401392
21  430 -0.167344  0.173274  1.386677   -10.401392
22  450 -0.223454  0.137372  1.386677   -10.401392
23  470 -0.199043  0.164989  1.386677   -10.401392
24  490  0.048659  0.153155  1.386677   -10.401392
25  510 -0.099772  0.135648  1.386677   -10.401392
26  530 -0.158866  0.190903  1.386677   -10.401392
27  550 -0.014600  0.147704  1.386677   -10.401392
28  570 -0.185739  0.222569  1.386677   -10.401392
29  590 -0.300033  0.195046  1.386677   -10.401392
30  610 -0.253054  0.225852  1.386677   -10.401392
31  630 -0.097743  0.234953  1.386677   -10.401392
32  650 -0.152919  0.225961  1.386677   -10.401392
33  670 -0.034817  0.251418  1.386677   -10.401392
34  690 -0.215592  0.259008  1.386677   -10.401392
35  710 -0.162534  0.258938  1.386677   -10.401392
36  730 -0.023826  0.248978  1.386677   -10.401392
37  750 -0.048769  0.246302  1.386677   -10.401392
38  770 -0.028856  0.274153  1.386677   -10.401392
39  790  0.055525  0.285260  1.386677   -10.401392
40  810 -0.139742  0.323907  1.386677   -10.401392
41  830 -0.055003  0.376917  1.386677   -10.401392
42  850 -0.062849  0.362402  1.386677   -10.401392
43  870 -0.122565  0.337064  1.386677   -10.401392
44  890 -0.015163  0.332197  1.386677   -10.401392
45  910  0.063167  0.352359  1.386677   -10.401392
46  930  0.029269  0.360472  1.386677   -10.401392
47  950 -0.077629  0.403610  1.386677   -10.401392
48  970 -0.087093  0.434666  1.386677   -10.401392
49  990 -0.062027  0.455545  1.386677   -10.401392